# Docker Compose для ShamsCloud - полная копия текущего проекта

services:
  # PostgreSQL база данных (точно как в текущем проекте)
  postgres:
    image: postgres:16-alpine
    container_name: shamscloud-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shamscloud
      POSTGRES_USER: shamscloud
      POSTGRES_PASSWORD: shamscloud_secure_password_2024
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamscloud -d shamscloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ShamsCloud приложение
  shamscloud:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: shamscloud-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Переменные базы данных (точно как в текущем проекте)
      DATABASE_URL: postgresql://shamscloud:shamscloud_secure_password_2024@postgres:5432/shamscloud
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: shamscloud
      PGPASSWORD: shamscloud_secure_password_2024
      PGDATABASE: shamscloud
      
      # Firebase конфигурация (точно из текущего проекта)
      VITE_FIREBASE_API_KEY: AIzaSyAEFPJACkDos0FIqPheMZJFAyqGJ67Hjb4
      VITE_FIREBASE_PROJECT_ID: shamscloud-c9e0f
      VITE_FIREBASE_APP_ID: 1:760344260491:web:65ec033f435192f871898e
      
      # Настройки приложения
      NODE_ENV: production
      PORT: 5000
      
      # Настройки безопасности
      SESSION_SECRET: shamscloud_super_secret_session_key_2024_production
      
    ports:
      - "5000:5000"
    volumes:
      # Постоянное хранение файлов пользователей
      - shamscloud_uploads:/app/uploads
      - shamscloud_data:/app/data
      - shamscloud_settings:/app/settings
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/auth/me"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx прокси (опционально, для production)
  nginx:
    image: nginx:alpine
    container_name: shamscloud-nginx
    restart: unless-stopped
    depends_on:
      - shamscloud
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_ssl:/etc/ssl
    profiles:
      - production

volumes:
  # Постоянные тома для данных
  postgres_data:
    driver: local
  shamscloud_uploads:
    driver: local
  shamscloud_data:
    driver: local  
  shamscloud_settings:
    driver: local
  nginx_ssl:
    driver: local

networks:
  default:
    name: shamscloud-network